name: Automatic Testing of EQquasi

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo bash ubuntu.env.setup.sh > testRunLog.txt || true

    - name: Run tests
      run: |
        bash make.scripts.executable.sh >> testRunLog.txt || true
        source install.eqquasi.sh >> testRunLog.txt || true
        python3 testAll.py >> testRunLog.txt || true
    
    - name: Check errors in testRunLog.txt
      run: |
        if grep -qiE 'error|Error|ERROR|exception|failed|fatal|abort' testRunLog.txt; then
            exit 1
        fi
    
    - name: Print log
      run: cat testRunLog.txt